Repository laminas/laminas-mvc-middleware, pull requests merged in 2025-03, with the labels that each got.

#46 Add support for PHP 8.4
  composer.json
  composer.lock
  src/HandlerFromPipeSpecFactory.php
  src/InvalidMiddlewareException.php
  src/MiddlewareController.php
  src/MiddlewareListener.php
  src/MiddlewareListenerFactory.php
  src/Module.php
  test/Integration/ApplicationBootstrapTest.php
  test/Integration/MiddlewareDispatchTest.php
  test/Integration/TestAsset/NoopSendResponseListener.php
  test/MiddlewareControllerTest.php
  test/MiddlewareListenerTest.php
  test/ModuleTest.php
  test/PipeSpecTest.php
  test/TestAsset/Middleware.php
Labels: Enhancement

#47 Upgrade Laminas Coding Standard to 3.x and Fix Docs Linting issues
  composer.json
  composer.lock
  docs/book/intro.md
Labels: QA

#48 Remove redundant `/intro.md` in favour of a configured redirect
  docs/book/intro.md
  mkdocs.yml
Labels: Documentation
